apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: order-service-trigger
spec:
  broker: order
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: order-service
